### ISSUE TITLE
Inaccurate image flash message

### ISSUE THREAD

**Issue by mo-nathan** [MushroomObserver/mushroom-observer#1895] opened 2024-02-11 10:59 UTC
The error level flash message, "Sorry, the image you tried to display (id #loading) does not exist. Someone may have deleted it or merged it into another.", is showing up when it shouldn't.

To reproduce:
Go to https://mushroomobserver.org/images/1486355
Click the light box expand widget in the upper right corner of the image
Close the light box image
Reload the page

I assume this has to do with some sort of lazy loading trigger some unexpected code path.  Note the "#loading" in the error message.

**Comment by JoeCohen** [comment] 2024-10-05 19:52
I'm closing this Issue as I cannot reproduce it and it appears to have been fixed.

**Closed by JoeCohen** 2024-10-05 19:52 UTC
Labels: bug
