### ISSUE TITLE
Click for map displays box instead of pin

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1744] opened 2023-12-25 19:05 UTC
Clicking lat/lon in show_observation should always display a map with a pin instead of a (2-dimensional) box. 
It fails in the following case, but works properly in every other case I've tried: 
(Might be an old issue.)
(iMac, Sonoma 14.2.1 (23C71), Chrome Version 120.0.6099.129 (Official Build) (x86_64)); also fails in Firefox 121.0
- https://mushroomobserver.org/448247
- Click [19.541°N 155.0733°W 365m [Click for map]](https://mushroomobserver.org/observations/448247/map)
Result:
<img width="485" alt="Screenshot 2023-12-25 at 10 47 37 AM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/bbc5fcd6-8eee-40ec-a47b-aa2c75d47034">

**Comment by nimmolo** [comment] 2023-12-26 04:05
This seems to be expected behavior, and I think there may be a different issue to address. Here's what's going on:

MO's single-obs map is built off a `MinimalMapObservation`, which calls `Location.lat_long_dubious?` to check if the observation's stated lat/lng are within or near the bounds of the declared Location (if there is one). If it's not close enough, the map will decide the lat/lng is dubious and show the Location box instead. 

In the case of this rural obs, the lat/lng does not fall within the declared bounds of Keaau, Hawaii, but it is near Keaau. 
```
# obs 448247
lat: 19.541
lng: -155.0733

# Keaau, HI
n: 19.6388
s: 19.6035
e: -155.024
w: -155.056
```
<img width="1013" alt="Screen Shot 2023-12-25 at 11 00 19 PM" src="https://github.com/MushroomObserver/mushroom-observer/assets/1948095/d99f6cd3-c1e7-45ac-9923-132c13ea7d29">

...and MO's definition of dubious is pretty strict:

```ruby
    # Is a given lat/long coordinate within or close to the bounding box?
    def lat_long_close?(lat, long)
      delta_lat = north_south_distance * 0.20
      delta_long = east_west_distance * 0.20
      return false if lat > north + delta_lat
      return false if lat < south - delta_lat

      if west <= east
        return false if long > east + delta_long
        return false if long < west - delta_long
      elsif long < west + delta_long && long > east - delta_long
        return false
      end
      true
    end
```

So... if there's an issue here, I think it's that rural observations may frequently lie outside a location they're identified with, when that location is a town. We may need to loosen our definition of dubious, in order to get these lat/lngs to show.

The `delta_lat` is closer to 2 than 0.2 here.

**Comment by nimmolo** [comment] 2023-12-26 04:12
This issue did prod me to clean up the map helpers, though! Just merged a small PR to make the args more transparent.

**Comment by JoeCohen** [comment] 2023-12-26 14:43
Thanks for the info. I didn't realize that!
And thanks for the cleanup.
How hard would it be to show both the lat/lon pin and the Location box? (Just thinking out loud.)

**Comment by nimmolo** [comment] 2023-12-26 18:36
That's an interesting idea. 

The data set returned for such an obs from `CollapsibleCollection` includes both `nsew` bounds and a `lat/lng` point already, it's just that the `dubious?` determination means the original obs lat/lng are overwritten by a calculation of the box center, and so the map never gets the original lat/lng. I'll check what it would take to include both. 

I still feel that a reconsideration of what "dubious" means might be preferable. When we think of small towns like Veneta or even Ashland, Oregon, the delta_lat between the town bounds and a place with that "location" as a postal address seems like it could well be 10x.

**Comment by JoeCohen** [comment] 2023-12-26 19:48
This is so low priority. Please don't spend a lot of time on it.

**Closed** 2024-03-19 22:01 UTC
